### ISSUE TITLE
repeat.for over map broken

### ISSUE THREAD

**Issue by egs-cm** [egs-cm/template-lint#36]

**Comment by egs-cm** [comment]
```
    An error occured while linting. TypeError: Cannot read properties of undefined (reading 'constructor')
        at BindingRule.examineBehaviorInstruction (/data/ssd/christianm/repo/egs-cm/template-lint/source/rules/bin
ding.ts:242:19)
        at BindingRule.examineAttribute (/data/ssd/christianm/repo/egs-cm/template-lint/source/rules/binding.ts:13
7:14)
        at BindingRule.examineElementNode (/data/ssd/christianm/repo/egs-cm/template-lint/source/rules/binding.ts:
113:12)
        at BindingRule.examineNode (/data/ssd/christianm/repo/egs-cm/template-lint/source/rules/binding.ts:72:12)
        at /data/ssd/christianm/repo/egs-cm/template-lint/source/rules/binding.ts:86:12
        at Array.forEach (<anonymous>)
        at BindingRule.examineNode (/data/ssd/christianm/repo/egs-cm/template-lint/source/rules/binding.ts:85:19)
        at /data/ssd/christianm/repo/egs-cm/template-lint/source/rules/binding.ts:86:12
        at Array.forEach (<anonymous>)
        at BindingRule.examineNode (/data/ssd/christianm/repo/egs-cm/template-lint/source/rules/binding.ts:85:19)
        at BindingRule.finalise (/data/ssd/christianm/repo/egs-cm/template-lint/source/rules/binding.ts:60:16)
        at /data/ssd/christianm/repo/egs-cm/template-lint/node_modules/template-lint/dist/linter.js:35:29
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async Promise.all (index 0)
```
